### ISSUE TITLE
Support a signaling server

### ISSUE THREAD

**Issue by daonb** [tuzig/webexec#58]
To support servers with no static IP, like home desktops behind a NAT, we need to add a signaling service.
The service connection parameters will be added to a new section in the conf file.

```toml
[peerbook]
email = "jrandomhacker@example.com"
host = "pb.terminal7.dev"
name = "host name"
```

The `host` and `name` are optional. The default host is pb.terminal7.dev and the default is the hostname.

## Additional context

On the client, the minimum signaling API must include:

- send a connection request with  to a server
- listen for servers' answers
